POST http://localhost:5000/api/url/shorten
Content-Type : application/json


{
    "longUrl":"https://www.flipkart.com/apple-ipad-pro-2021-3rd-generation-8-gb-ram-128-rom-11-inches-wi-fi-only-space-grey/p/itm864a8b429a48b?pid=TABG2DM4Q2FTMGG7&lid=LSTTABG2DM4Q2FTMGG7EFIAAW&marketplace=FLIPKART&q=ipad&store=tyy%2Fhry&srno=s_1_7&otracker=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&fm=SEARCH&iid=7e95f41a-4503-4ea1-941b-7c35fa0ae460.TABG2DM4Q2FTMGG7.SEARCH&ppt=clp&ppn=elec-b2b-store&ssid=adnwg4iegg0000001638990842996&qH=09401fded433c347"
}